default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: max
  password:

development:
  <<: *default
  database: education_development


test:
  <<: *default
  database: education_test
