default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: furetur
  password: password

development:
  <<: *default
  database: education_development

test:
  <<: *default
  database: education_test
