default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: max
  password: 123

development:
  <<: *default
  database: education_development

test:
  <<: *default
  database: education_test
