default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: kirill
  password: 

development: 
  <<: *default
  database: education_development


test:
  <<: *default
  database: education_test